### PR TITLE
Create ex_opencv.py

### PR DESCRIPTION
**Pull request by matthijs876**
I have been looking for an alternative to manually downloading maps from the google api and plotting points on it in opencv and have been unable to find one untill i came across this library, it is easy to convert a pil image to opencv, so that is what i did, and added some things to be able to zoom and plot points. I have not been able to add a buffer to this, but I have never worked with asyncio before and don't understand it at present.
This is also my first ever contribution to github, so please provide feedback.

### CODE REVIEW

**Comment by wrobell** [comment]
Thanks for the example.

Do you mind if I ask you to improve the coding style a bit? Please take
a look at other examples (i.e. ``examples/ex-qt-gps.py``).  You can also use
``pep8`` module to check

```
python3 -m pep8 ex_opencv.py
```

**Comment by matthijs876** [comment]
I edited the example according to your request, please take another look at it

**Comment by wrobell** [comment]
This needs bit more work. I will merge the pull request and clean few things. I hope this is OK. Give me few days.

**Comment by matthijs876** [comment]
Ofcourse this is OK, i am trying to learn something here :)
Thanks for taking the time to look at it

**Comment by wrobell** [comment]
I have merged the changes, renamed the file and put licensing header there. Please let me know if you disagree with the licensing.

The example docstring references your GitHub account. Should I replace it with your name and e-mail?

**Comment by wrobell** [comment]
matthijs876, could you please confirm you are ok with the license text in your example?

**Comment by matthijs876** [comment]
Looks fine to me!
If you have time, could you please show how this example could be extended to include a cashing algorithm without using redis? I am currently using this to show the path my drone follows, but i would like te be able to zoom and move the map without the delay it currently has.

Kind regards,
Matthijs

**Comment by wrobell** [comment]
Thanks, I have compiled OpenCV with Python 3 and will do some more changes while testing it.

For caching, please create new issue and please show some code, so we can discuss it.

**Comment by matthijs876** [comment]
i never bothered compiling opencv my self, i always download precompiled binaries from http://www.lfd.uci.edu/~gohlke/pythonlibs/#opencv

**Comment by wrobell** [comment]
I have updated the example bit more. It is done now.

**Comment by matthijs876** [comment]
Thanks for all the edits you made to the open-cv example, I hope I learn something from it :)
I was able to solve my cashing issue after all, I am not using redis, for some reason i couldn't get it to work on my windows computer properly, so i created a caching downloader using the python shelve module. If you are interested in the code i could upload it for you.

**Comment by wrobell** [comment]
Caching downloader using `shelve` would be great.

**Pull request merged**
